export const MODULE_LABELS: Record<string, string> = {
  admin: "Administration",
  org: "Organigramme et processus",
  models: "Générateur de modèles",
  catalog: "Articles et services",
  clients: "Clients",
  sales: "Ventes",
  expenses: "Dépenses",
  forecasts: "Prévisions et écarts",
  hr: "Ressources humaines",
  purchasing: "Achats",
  stock: "Stock",
  production: "Production",
  crm: "Relation client",
  projects: "Projets et marchés",
  logistics: "Logistique",
  documents: "Documents",
  reports: "Requêtes et états",
  dashboards: "Tableaux de bord",
  audit: "Journal d'audit",
};

export const MODULE_NAV: { key: string; href: string; label: string }[] = [
  { key: "dashboards", href: "/dashboard", label: "Tableau de bord" },
  { key: "org", href: "/org", label: "Organigramme" },
  { key: "clients", href: "/clients", label: "Clients" },
  { key: "catalog", href: "/catalog", label: "Articles & services" },
  { key: "sales", href: "/sales", label: "Ventes" },
  { key: "expenses", href: "/expenses", label: "Dépenses" },
  { key: "forecasts", href: "/forecasts", label: "Prévisions & écarts" },
  { key: "hr", href: "/hr", label: "Ressources humaines" },
  { key: "purchasing", href: "/purchasing", label: "Achats" },
  { key: "stock", href: "/stock", label: "Stock" },
  { key: "crm", href: "/crm", label: "Relation client" },
  { key: "projects", href: "/projects", label: "Projets & marchés" },
  { key: "logistics", href: "/logistics", label: "Logistique" },
  { key: "reports", href: "/reports", label: "Requêtes & états" },
  { key: "documents", href: "/documents", label: "Documents" },
  { key: "audit", href: "/audit", label: "Journal d'audit" },
  { key: "admin", href: "/admin", label: "Administration" },
];
