-- ============================================================
-- Catalogue des secteurs d'activité (section 2.2 du cahier des charges)
-- ============================================================
insert into public.sectors (key, name) values
  ('pharmacie', 'Pharmacie'),
  ('clinique', 'Clinique'),
  ('cabinet_medical', 'Cabinet médical ou professionnel'),
  ('garage_automobile', 'Garage automobile'),
  ('mecanique', 'Mécanique'),
  ('cycles_pieces', 'Cycles et pièces détachées'),
  ('menuiserie', 'Menuiserie'),
  ('salon_coiffure', 'Salon de coiffure'),
  ('cosmetique', 'Cosmétique'),
  ('habillement', 'Habillement et vente vestimentaire'),
  ('atelier_couture', 'Atelier de couture'),
  ('centre_formation', 'Centre de formation'),
  ('etablissement_scolaire', 'Établissement scolaire'),
  ('btp', 'BTP'),
  ('imprimerie', 'Imprimerie'),
  ('bureautique', 'Bureautique'),
  ('informatique', 'Informatique'),
  ('commerce_general', 'Commerce général'),
  ('metallurgie', 'Métallurgie'),
  ('scierie', 'Scierie'),
  ('briqueterie', 'Briqueterie'),
  ('energie_solaire', 'Énergie solaire'),
  ('import_export', 'Import-export'),
  ('quincaillerie', 'Quincaillerie'),
  ('restauration', 'Restauration'),
  ('cafe', 'Café'),
  ('bar', 'Bar'),
  ('cybercafe', 'Cybercafé'),
  ('agroalimentaire', 'Agroalimentaire'),
  ('aviculture', 'Aviculture'),
  ('porciculture', 'Porciculture'),
  ('pisciculture', 'Pisciculture'),
  ('embouche_bovine', 'Embouche bovine'),
  ('embouche_ovine', 'Embouche ovine'),
  ('agriculture', 'Agriculture'),
  ('apiculture', 'Apiculture'),
  ('laiterie', 'Laiterie'),
  ('fromagerie', 'Fromagerie'),
  ('fruits_legumes', 'Fruits et légumes'),
  ('cereales', 'Céréales'),
  ('ecomateriaux', 'Écomatériaux'),
  ('tourisme', 'Tourisme'),
  ('hotellerie', 'Hôtellerie'),
  ('hebergement', 'Hébergement'),
  ('art_peinture', 'Art et peinture'),
  ('associations', 'Associations'),
  ('centre_culturel', 'Centre culturel'),
  ('securite_gardiennage', 'Sécurité et gardiennage'),
  ('hydrocarbures', 'Hydrocarbures'),
  ('station_service', 'Station-service'),
  ('transport', 'Transport'),
  ('transit', 'Transit'),
  ('forages', 'Forages'),
  ('agence_voyage', 'Agence de voyage'),
  ('sport', 'Sport'),
  ('distribution', 'Distribution')
on conflict (key) do nothing;
